# Workflow Name
name : First Workflow
# Trigger
on : 
  push :
  workflow_dispatch:
 
jobs:
  #First Job
  Hello-job:
     # runner - Github hosted
     runs-on : ubuntu-latest
     steps:
       - name : Hello World
         run : echo "Hello World"
       - name : Event Name
         run : echo "Event Name :${{github.event_name}}" # context reference
  
# Second Job
  echo-Goodbye:
    needs : Hello-job
    runs-on : ubuntu-slim
    steps:
      - name: Say Goodbye
        run : echo "Good Bye!"
         # multiline commands
      - name : Multi-line bash
        run : |
         echo "I am"
         echo "multi-line"
         echo "script"
# Third Job
  windows-echo:
    if: github.event_name == 'workflow_dispatch'
    runs-on : windows-latest
    steps:
      - name : Show OS
        shell : bash
        run : echo "The job is runninng on windows runner"
